// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqZf7XBeUoXx6sxcms_dJ7yvTQjKJSU4',
    appId: '1:502308356491:web:db13c5e472dc197b72ef8e',
    messagingSenderId: '502308356491',
    projectId: 'hackskills2303',
    authDomain: 'hackskills2303.firebaseapp.com',
    storageBucket: 'hackskills2303.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgaLlfLlKPMnvQuOLa7Lu3otxjq63chLU',
    appId: '1:502308356491:android:7cae2a2a6c01188372ef8e',
    messagingSenderId: '502308356491',
    projectId: 'hackskills2303',
    storageBucket: 'hackskills2303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxkMcOcrnno-srvNDpFze9S7WvmnGlz8',
    appId: '1:502308356491:ios:ab7919df2f9e66df72ef8e',
    messagingSenderId: '502308356491',
    projectId: 'hackskills2303',
    storageBucket: 'hackskills2303.appspot.com',
    iosClientId: '502308356491-3givd11am3ngvtaaeigjbjpdi81ekdu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hack2skill',
  );
}
